#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#i_default_operator_rewards;
pub mod r#i_default_operator_rewards_factory;
pub mod r#i_default_staker_rewards;
pub mod r#i_default_staker_rewards_factory;
pub mod r#i_staker_rewards;
pub mod r#i_staker_rewards_claim;
